### ISSUE TITLE
Port audio

### ISSUE THREAD

**Issue by gsg2016** [shivasiddharth/DIY-Echo-Show#1]
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... 
http://www.portaudio.com/archivesfailed: 
Connection timed out.
Retrying.

Looks like the Site is down. Hopefully not for long

**Comment by jsginkc** [comment]
Mine is stuck here. 
--2020-07-29 01:37:35--  (try: 8)  http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Retrying.

**Comment by shawnpaffhausen** [comment]
same here with the port audio failing

**Comment by shawnpaffhausen** [comment]
Fixed mine by reconfiguring the voice installer script with a version of port audio now it's stuck at 95% with some complier

**Comment by shivasiddharth** [comment]
You need a lot of patience and time.

**Comment by shawnpaffhausen** [comment]
Been running since last night could it be related to kernel issue with respeaker of portaudioSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: shivasiddharth <notifications@github.com> Date: 7/30/20  10:20  (GMT-05:00) To: shivasiddharth/DIY-Echo-Show <DIY-Echo-Show@noreply.github.com> Cc: shawnpaffhausen <shawnpaffhausen@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [shivasiddharth/DIY-Echo-Show] Port audio (#1) 
You need a lot of patience and time.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/1#issuecomment-666394748",
"url": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/1#issuecomment-666394748",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by antonjudes** [comment]
You can download port audio from below link
https://github.com/antonjudes/portaudio

and save contents to /home/pi/DIY-Echo-Show/Alexa/thirdparty/portaudio 

Open /home/pi/DIY-Echo-Show/Alexa/setup.sh
Under **build_port_audio(){** add hash for below lines to bypass download portaudio
# wget -c $PORT_AUDIO_DOWNLOAD_URL
# tar zxf $PORT_AUDIO_FILE

Clear the build folder under DIY-Echo-Show
Continue with step 8
sudo /home/pi/DIY-Echo-Show/scripts/alexa-voice-installer.sh

**Comment by shivasiddharth** [comment]
Portaudio is back up and running
